name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y cmake g++ libgtest-dev

    - name: Configure and Build
      run: |
        cmake -B build
        cmake --build build --parallel 2

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
